[[pages]]
path = "Welcome.py"
name = "Home"
icon = "ğŸ”¬"


[[pages]]
path = "pages/a_File_Upload.py"
name = "File_Upload"
icon = "ğŸ“‚"


[[pages]]
path = "pages/b_Interaction_Analysis.py"
name = "Pairwise interactions"
icon = "ğŸ”"

[[pages]]
path = "pages/c_Residue_Depth_plotly.py"
name = "Residue Depth"
icon = "ğŸ“ˆ"


[[pages]]
path = "pages/d_Energy_Heatmap.py"
name = "Energy difference heatmap"
icon = "ğŸ”¥"